### ISSUE TITLE
Technical restrictions

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-cw#1]
I had small technical questions for the compiler:
- Do we have to build it with C++? If not, is Java supported on the testing machines?
- Are we limited to use yacc / lex? If not, are there any restrictions on public automation tools?
- For the parser grammar, there are some publicly available C grammar templates. Can we use these and add a reference to the ressources?

**Comment by johnwickerson** [comment]
Hi Jaafar, 

You don't have to use C++; Java is fine. It would be appreciated if you could modify the vagrantfile that is provided so that it includes Java and all the necessary components to make your compiler work.

You don't have to use Yacc/Lex/Bison/Flex; other publicly available automation tools are fine. Please add them to the vagrantfile if you use them. 

Be aware that it's somewhat risky to use a different language for implementing the compiler compared to the rest of your class. For instance, your GTAs have more expertise in C++ than in Java, so will not be able to provide as much assistance.

Yes, I'm aware that there are plenty of publicly available C grammars. Beware that these are rather complicated though, as they tend to cover the language in all its gory generality! You *might* prefer to start from a smaller grammar and then add on support for more language features as the project progresses.

**Comment by JaafarRammal** [comment]
Thank for the detailed answer (will follow the advice).

Just to confirm for the grammar, we can therefore use open-source grammars (either partially or fully)?

**Comment by ymherklotz** [comment]
Yes, you are allowed to use existing open-source grammars, but these might be very general and complex. As John mentioned, it might therefore be easier to start with a smaller subset of the grammar.

In addition to that, the whole C language does not have to be supported (such as gotos) so using the full grammar will leave some rules unused.
