### ISSUE TITLE
Initialization list

### ISSUE THREAD

**Issue by Lukacma** [LangProc/langproc-2019-cw#25]
I have a question about the initialization list. Do its values have to be a constant expression or not? I am finding conflicting information online so I would like to make sure.

**Comment by ymherklotz** [comment]
So actually it does seem to be ambiguous. In the [standard](http://port70.net/~nsz/c/c89/c89-draft.html#initializer) that I was looking at, any expression should be allowed in the initialiser list.

However, when I compile the following code

```c
int main() {
    int y = 1;
    int a[2] = {y, 2};
    return a[0];
}
```

with

```
gcc -Wall -Wextra -std=c89 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition main.c
```

I get the following warning:

```
main.c:5:17: warning: initializer for aggregate is not a compile-time constant [-Wc99-extensions]
    int a[2] = {y, 2};
                ^
1 warning generated.
```

So it seems that GCC thinks it is a C99 extension.

Because of this, I think only constants will be tested in the initialiser list.

**Comment by ymherklotz** [comment]
Actually my bad, it's not ambiguous, the standard does say:

> All the expressions in an initializer for an object that has static storage duration or in an initializer list for an object that has aggregate or union type shall be constant expressions. 

So they do have to be constant expressions.

**Comment by JaafarRammal** [comment]
@ymherklotz suppose we have an array of doubles. Can we assume the initialization in the global scope will never exceed 64 bits per constant?

**Comment by ymherklotz** [comment]
I think so? I can't think of a counter example.

**Comment by JaafarRammal** [comment]
@ymherklotz 

Will we be tested on the following:

```
int a[3] = {[0...1] = 3};
```
