### ISSUE TITLE
Implicit type conversion for function invocations

### ISSUE THREAD

**Issue by AdrianKoch3010** [LangProc/langproc-2019-cw#29]
For function invocations, can we assume that the types of the expressions passed to the function are the same as the types of the parameters the function has been declared/defined with; or do we have to account for implicit type conversion?

For example, say the function was declared as foo(unsigned int), will it ever be called like this: foo(-1)?
And if yes, do we have to deal with declarations in the form of foo() that don't specify any of the parameter types?

**Comment by ymherklotz** [comment]
Implicit type conversions don't have to be supported, see [here](https://github.com/LangProc/langproc-2019-cw/issues/28#issuecomment-596810181). I'm not sure though if `foo(-1)` for `foo(unsigned)` actually violates that, because it should be implemented automatically, you wouldn't actually have to do any casting for it to work I believe.

Declarations of the form `foo()` should be supported though, they are just function calls without arguments.
